name: Github Action Example for EnvKey

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: synchealthlabs/github-action-envkey@main
      env:
        ENVKEY: ${{ secrets.ENVKEY }}
    - name: Show environment
      run: env